Refactor component to use new tokens, and component dependencies (text, icon).
selsa-inube/inubekit-button pull request #2
Opened 2024-02-28 22:19 UTC by cmarin001

This pull request outlines the comprehensive refactoring of a specific UI component to leverage new design tokens and updated dependencies, including text and icon components. Aimed at aligning the component with our evolving design system and improving its interoperability within the application, this refactoring ensures a more consistent, efficient, and maintainable implementation.

2024-02-29 14:30 UTC, JanuarAsprilla approved these changes

2024-03-01 22:03 UTC, wfercanas requested changes

2024-03-01 22:03 UTC, wfercanas commented on vite.config.ts
> +      external: [
El build está ocupando 24kb porque no estamos incluyendo aquí `react-router-dom`

2024-03-02 18:14 UTC, cmarin001 commented on src/Button/index.tsx
solved

2024-03-02 18:17 UTC, cmarin001 commented on vite.config.ts
> +      external: [
solved

2024-03-04 21:15 UTC, cmarin001 commented on src/Button/index.tsx
> +function childrenAppearence(
solved

2024-03-05 10:25 UTC, JanuarAsprilla approved these changes

2024-03-07 20:12 UTC, cmarin001 commented on package.json
>      "@inubekit/stack": "^1.1.0",
solved

2024-03-07 20:12 UTC, cmarin001 commented on package.json
> +    "@inubekit/icon": "^1.2.0",
solved

2024-03-11 15:28 UTC, wfercanas requested changes

2024-03-11 15:28 UTC, wfercanas commented on src/Button/index.tsx
>                cursorHover={cursorHover}
The text and the icon components shouldn't change because of a hover when the button is filled. When filled, only the background should change, not the text nor the icon.

When the icon is outlined or none, the text and icon should allow its hover state to work, even when those components are not directly hovered. If the user moves the cursor over the border of the button, the border, text and icon should be highlighted.

2024-03-11 21:07 UTC, cmarin001 commented on src/Button/index.tsx
>                cursorHover={cursorHover}
solved

2024-03-11 23:06 UTC, JanuarAsprilla approved these changes

2024-03-12 03:11 UTC, wfercanas requested changes

2024-03-12 03:11 UTC, wfercanas commented on src/Button/index.tsx
> +              parentHover={variant === "filled" ? false : parentHover}
This adjustment seems insufficient to achieve the desired result.

If we see the cursorHover and parentHover props of icons or texts, they work like this:
1. **cursorHover:** determines if the component itself should react to a cursor hover. If the :hover state should be activated.
2. **parentHover:** triggers the :hover state in the component even though the cursor is not exactly above the component. This is used to force the component into a :hover state because its parent requires it.

Therefore, both icon and text should be defined as follows:
1. **cursorHover + filled:**  if the button is filled, the cursorHover property should **always be false**.
2. **cursorHover + outlined:** in this case, the cursor :hover should also be **always false**, because we want to trigger the :hover state exactly when the cursor is over the button, not just over the icon or text.
3. **parentHover + filled:** this scenario is **always false**, since for all filled buttons both text and icons remain unchanged.
4. **parentHover + outlined:** this scenario must be **true sometimes**, because we need to light up texts and icons to highlight that the whole button is being hovered. It is not desirable that the icon lights up only when the cursor is over it.

To achieve the last option, we must catch the hover on the button, which can be achieved with the onMouseEnter event. Also we need the onMouseLeave event to know that the button is no longer being hovered.

So, we can have a state to save if the button is being hovered or not. With that knowledge, we can then change parentHover prop between false and true depending of the current state and then properly light up those children components.

**Note:** check if the default value of cursorHover is false. If so, then we can omit its usage here.

2024-03-12 22:27 UTC, cmarin001 commented on src/Button/index.tsx
> +              parentHover={variant === "filled" ? false : parentHover}
solved

2024-03-12 22:35 UTC, JanuarAsprilla approved these changes

2024-03-13 14:29 UTC, wfercanas approved these changes

2024-03-13 14:29 UTC, merged